# Homebrew Bundle
# https://github.com/Homebrew/homebrew-bundle

# CLI Tools
brew "zsh"
brew "sheldon"
brew "coreutils"
brew "tree"
brew "wget"
brew "yarn"
brew "tldr"
brew "mas"
brew "openssl@3"
brew "spaceship"

# Desktop applications
cask "gpg-suite"
cask "telegram"
cask "google-chrome"
cask "firefox"
cask "dropbox"
cask "vlc"
cask "iterm2"
cask "visual-studio-code"
cask "slack"
cask "steam"
cask "transmission"
cask "handbrake"
cask "github"
cask "spotify"
cask "atom"
cask "tradingview"
cask "latexit"
cask "zettlr"
cask "zotero"
cask "discord"
cask "mactex"
# Python
brew pyenv

# Quick Look plugins
cask "qlcolorcode" # https://github.com/anthonygelibert/QLColorCode
cask "qlstephen" # https://github.com/whomwah/qlstephen
cask "quicklook-json" # https://github.com/sindresorhus/quick-look-plugins
cask "qlimagesize" # https://github.com/Nyx0uf/qlImageSize
cask "webpquicklook" # https://github.com/dchest/webp-quicklook

# MacAppstore
mas install 1333542190 # 1password vault
mas install 441258766 # Magnet
